package com.masai.Service;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.masai.exception.ApplicationException;
import com.masai.model.Admin;
import com.masai.model.Category;
import com.masai.model.Customer;
import com.masai.model.Product;
import com.masai.repository.AdminRepository;
import com.masai.repository.CategoryRepository;
import com.masai.repository.CustomerRepository;
import com.masai.repository.ProductRepository;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class AdminServicesInterfaceImplimentation implements AdminServicesInterface {
	@Autowired
	private AdminRepository aRepo;
	@Autowired
	private ProductRepository pRepo;
	@Autowired
	private CategoryRepository cRepo;
	@Autowired
	private CustomerRepository cuRepo;
//	@Autowired
//	private PasswordEncoder pass;
	
	@Override
	public void addAdmin(Admin admin) throws ApplicationException {
		log.info("Admin is Adding customer in Service Layer");
		Optional<Admin> opt = aRepo.findById(admin.getAdminId());
		if(opt.isPresent()) {
			throw new ApplicationException("Already Exists with these credentials...");
		}
		if(admin.getAdminId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		if(admin==null) throw new ApplicationException("Fields don't have any data");
//		admin.setPassword(pass.enCode(admin.getPassword()));
		aRepo.save(admin);
		
	}
	@Override
	public void updateAdmin(Integer adminId,Admin admin) throws ApplicationException{
		log.info("Admin is Updating an Admin Details in Service Layer");
		Optional<Admin> opt = aRepo.findById(adminId);
		if(opt.isEmpty()) {
			throw new ApplicationException("No Admin Found with this ID...");
		}
		if(admin.getAdminId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		if(admin==null) throw new ApplicationException("Fields don't have any data");
		opt.get().setName(admin.getName());
		opt.get().setMailOrUsername(admin.getMailOrUsername());
//		opt.get().setPassword(pass.enCode(admin.getPassword()));
		opt.get().setPassword(admin.getPassword());
		aRepo.save(opt.get());
		
	}
	@Override
	public void deleteAdmin(Integer adminId)throws ApplicationException {
		log.info("Admin is Deleting an Admin in Service Layer");
		Optional<Admin> opt = aRepo.findById(adminId);
		if(opt.isEmpty()) {
			throw new ApplicationException("No Admin Found with these Details...");
		}
		opt.get().setActive(false);
		aRepo.save(opt.get());
	}
	@Override
	public void deleteCustomer(Integer customerId) throws ApplicationException {
		log.info("Admin is Deleting a Customer in Service Layer");
		Optional<Customer> opt = cuRepo.findById(customerId);
		if(opt.isEmpty()) {
			throw new ApplicationException("No Admin Found with these Details...");
		}
		opt.get().setActive(false);
		cuRepo.save(opt.get());
	}
	
	
	
	
	@Override
	public void addProduct(int cateId,Product product) throws ApplicationException {
		log.info("Admin is Adding Product in Service Layer");
		Optional<Product> opt = pRepo.findById(product.getProductId());
		if(opt.isPresent()) {
			throw new ApplicationException("Already Exists with these Details...");
		}
		if(product.getProductId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		if(product==null) throw new ApplicationException("Fields don't have any data");
		Optional<Category> optt = cRepo.findById(cateId);
		if(optt.isEmpty()) {
			throw new ApplicationException("No Category Found with this ID...");
		}
		optt.get().getProducts().add(product);
		product.setCategory(optt.get());
		pRepo.save(product);
	}
	@Override
	public void updateProduct(Integer productId, Product product) throws ApplicationException {
		log.info("Admin is Updating Product in Service Layer");
		Optional<Product> opt = pRepo.findById(product.getProductId());
		if(opt.isEmpty()){
			throw new ApplicationException("No Product Found with this ID...");
		}
		if(product.getProductId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		if(product==null) throw new ApplicationException("Fields don't have any data");
		opt.get().setAvailablility(product.getAvailablility());
		opt.get().setCategory(product.getCategory());
		opt.get().setDescription(product.getDescription());
		opt.get().setImageUrl(product.getImageUrl());
		opt.get().setName(product.getName());
		opt.get().setPrice(product.getPrice());
		pRepo.save(opt.get());
	}
	@Override
	public void deleteProduct(Integer productId) throws ApplicationException{
		log.info("Admin is Deleting Product in Service Layer");
		Optional<Product> opt = pRepo.findById(productId);
		if(opt.isEmpty()){
			throw new ApplicationException("No Product Found with this ID...");
		}
		opt.get().setActive(false);
		pRepo.save(opt.get());
	}
	
	
	
	@Override
	public void addCategory(Category category) throws ApplicationException{
		log.info("Admin is Adding Category in Service Layer");
		Optional<Category> opt = cRepo.findById(category.getCategoryId());
		if(opt.isPresent()) {
			throw new ApplicationException("Already Exists with these Details...");
		}
		if(category.getCategoryId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		if(category==null) throw new ApplicationException("Fields don't have any data");
		cRepo.save(category);
	}
	public void deleteCategory(Integer categoryId) throws ApplicationException{
		log.info("Admin is Deleting a category in Service Layer");
		Optional<Category> opt = cRepo.findById(categoryId);
		if(opt.isEmpty()) {
			throw new ApplicationException("No Category Found with this ID...");
		}
		opt.get().setActive(false);
		for(Product product:opt.get().getProducts()) {
			product.setCategory(null);
			product.setActive(false);
		}
		cRepo.save(opt.get());
	}
	@Override
	public void updateCategory(Integer categoryId, Category category)throws ApplicationException{
		log.info("Admin is Updating a category in Service Layer");
		Optional<Category> opt = cRepo.findById(categoryId);
		if(opt.isEmpty()) {
			throw new ApplicationException("No Category Found with this ID...");
		}
		if(category.getCategoryId()!=0) {
			throw new ApplicationException("Id is AutoGenerated Type Don't mention it...");
		}
		if(category==null) throw new ApplicationException("Fields don't have any data");
		opt.get().setName(category.getName());
		cRepo.save(opt.get());
	}
	@Override
	public List<Admin> getAllAdmin()throws ApplicationException{
		List<Admin>admins = aRepo.findAll();
		if(admins.size()==0) {
			throw new ApplicationException("No Admin Found");
		}
		return admins;
	}
	@Override
	public List<Product> getAllProduct()throws ApplicationException{
		List<Product>products = pRepo.findAll();
		if(products.size()==0) {
			throw new ApplicationException("No Admin Found");
		}
		return products;
	}
	@Override
	public List<Category> getAllCategory()throws ApplicationException{
		List<Category>categories = cRepo.findAll();
		if(categories.size()==0) {
			throw new ApplicationException("No Admin Found");
		}
		return categories;
	}
//	@Override
//	public Admin getDetails(String email)throws ApplicationException {
//		
//		return aRepo.findByEmail(email).orElseThrow(() -> new ApplicationException("Customer Not found with Email: "+email));
//	}

}
